angelhack/angelhack/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^admin/', admin.site.urls),
    url(r'^issue/', include('issues.urls', namespace='issues')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

angelhack/home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sign-up$', views.signup, name='signup'),
    url(r'^sign-in$', views.signin, name='signin'),
    url(r'^sign-out$', views.signout, name='signout'),
    url(r'^daily-routine$', views.dailyroutine, name='routine'),
]

angelhack/issues/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from . import views

admin.autodiscover()

urlpatterns = [
    url(r'^test_geolocation/$', views.location, name='geolocation'),
    url(r'^submit$', views.submit, name='submit'),
    url(r'^me$', views.me, name='me'),
    url(r'^all$', views.all, name='all'),
    url(r'^(?P<issue_id>[0-9]+)/images$', views.images, name='images'),
    url(r'^(?P<issue_id>[0-9]+)$', views.details, name='details'),
]

angelhack/issues/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

STATUS_ISSUE = (
    ('waiting_picture', "Waiting for first picture"),
    ('online', "Online"),
    ('resolved', "Resolved"),
    ('duplicate', "Duplicate"),
    ('closed', "Closed"),
)

class Category(models.Model):
    title = models.CharField(max_length=70)
    respected = models.ForeignKey(User, default=1)
    
    def __str__(self):
        return self.title

class Tag(models.Model):
    title = models.CharField(max_length=70)
    
    def __str__(self):
        return self.title

class Issue(models.Model):
    title = models.CharField(max_length=70)
    summary = models.TextField(max_length=700)
    description = models.TextField(max_length=5000)
    author = models.ForeignKey(User, null=True)
    status = models.CharField(max_length=40, choices=STATUS_ISSUE, default='waiting_picture')

    category = models.ForeignKey(Category, blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True)

    latitude = models.FloatField(default=0.0)
    longitude = models.FloatField(default=0.0)
    
    date_created = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(null=True)
    
    def __str__(self):
        return self.title

class Image(models.Model):
    file = models.ImageField(upload_to="issue-img/")
    title = models.CharField(max_length=70)
    summary = models.TextField(max_length=700, null=True, blank=True)
    issue = models.ForeignKey(Issue)
    
    def __str__(self):
        return self.title

angelhack/issues/forms.py
from django import forms
from .models import *

class SubmitIssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ('title', 'summary', 'description', 'tags', 'latitude', 'longitude', 'category')

    def __init__(self, *args, **kwargs):
        super(SubmitIssueForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['summary'].widget.attrs.update({'class': 'form-control', 'rows': '2'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})
        self.fields['tags'].widget.attrs.update({'class': 'form-control select2tags'})
        self.fields['latitude'].widget.attrs.update({'class': 'form-control'})
        self.fields['longitude'].widget.attrs.update({'class': 'form-control'})
        self.fields['category'].widget.attrs.update({'class': 'form-control select2select'})

class AddImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['title', 'file', 'summary']

    def __init__(self, *args, **kwargs):
        super(AddImageForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['summary'].widget.attrs.update({'class': 'form-control', 'rows': '2'})

angelhack/issues/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.utils import timezone
from .forms import *
from .models import *

def location(request):
    if request.POST:
        print(request.POST['lat'], request.POST['lng'])
        print("Got coordinates: ", request.POST['lat'], request.POST['lng'])
        return HttpResponse("You just sent me the coordinates: %s %s" % (str(request.POST['lat']), str(request.POST['lng'])))
    else:
        print("Empty call")
        return render(request, 'issues/index.html')

def submit(request):
    if not request.user.is_authenticated():
        messages.error(request, "You must be logged in to submit an issue")
        return redirect(reverse('home:signin'))
    if request.method == 'POST':
        form = SubmitIssueForm(request.POST)
        if form.is_valid():
            form.save()
            issue = Issue.objects.all().order_by('-id').first()
            issue.author = request.user
            issue.save()
            form = SubmitIssueForm()
            messages.success(request, "The issue has been submitted")
            messages.info(request, "You can now add images to your issue")
            return redirect(reverse('issues:images', kwargs={'issue_id': issue.id}))
        else:
            messages.warning(request, "The data received are invalid")
    else:
        form = SubmitIssueForm()
    return render(request, "issues/submit.html", {'form': form})

def images(request, issue_id):
    if not request.user.is_authenticated():
        messages.error(request, "You must be logged in to send an image")
        return redirect(reverse('home:signin'))
    issue = Issue.objects.get(id=issue_id)
    if request.method == 'POST':
        form = AddImageForm(request.POST, request.FILES)
        if form.is_valid():
            newfile = Image(file=request.FILES['file'])
            newfile.title = form.cleaned_data['title']
            newfile.summary = form.cleaned_data['summary']
            newfile.issue = issue
            newfile.save()
            form = AddImageForm()
            issue = Issue.objects.get(id=issue_id)
            if issue.image_set.all().count() > 0:
                if issue.status == 'waiting_picture':
                    issue.status = 'online'
                    issue.save()
            messages.success(request, "The image has been uploaded")
        else:
            messages.warning(request, "The data received are invalid")
    else:
        form = AddImageForm()
    issue = Issue.objects.get(id=issue_id)
    return render(request, "issues/images.html", {"issue": issue, "form": form})

def details(request, issue_id):
    issue = Issue.objects.get(id=issue_id)
    return render(request, "issues/details.html", {"issue": issue})
    

def me(request):
    if not request.user.is_authenticated():
        messages.error(request, "You must be logged in to access this page")
        return redirect(reverse('home:signin'))
    return render(request, "issues/me.html", {"issues": Issue.objects.filter(author=request.user).order_by("-date_created")})

def all(request):
    return render(request, "issues/all.html", {"issues": Issue.objects.filter(status='online').order_by("-date_updated")})

angelhack/issues/templates/issues/all.html
{% extends "home/base.html" %}
{% load status %}

{% block title %}All issues{% endblock %}

{% block content %}
<h1>All issues</h1>
{% if issues.count == 0 %}
<p>There is no issues reported yet.</p>
{% else %}
<div class="list-group">
  {% for issue in issues %}
  <div class="list-group-item">
    <h4 class="list-group-item-heading"><a href="{% url 'issues:details' issue.id %}">{{ issue.title }}</a></h4>
    <p class="list-group-item-text text-muted">{{ issue.author.first_name }} - {{ issue.date_created }}</p>
    <p class="list-group-item-text">{{ issue.tags.all|join:", " }}</p>
  </div>
  {% endfor %}
</div>
{% endif %}
{% endblock %}

angelhack/issues/templates/issues/details.html
{% extends "home/base.html" %}
{% load status %}

{% block title %}{{ issue.title }}{% endblock %}

{% block content %}
<h1>{{ issue.title }}</h1>
{% if user == issue.author %}
<ul class="nav nav-tabs">
  <li class="active"><a href="{% url 'issues:details' issue.id %}">Details</a></li>
  <li><a href="{% url 'issues:images' issue.id %}">Add images</a></li>
</ul>
{% endif %}
<p>Category: {{ issue.category.title }}</p>
<p>Tags: {{ issue.tags.all|join:", " }}</p>
<p>Issue reported by {{ issue.author.first_name }} on {{ issue.date_created }}</p>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    {% for image in issue.image_set.all %}
    <div class="item {% if forloop.first %}active{% endif %}">
      <div class="text-center">
	<img src="{{ image.file.url }}" alt="{{ image.title }}"/>
	</div>
      <div class="carousel-caption">
	{{image.title}}
      </div>
    </div>
    {% endfor %}
  </div>
  
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

{% endblock %}

angelhack/issues/templates/issues/images.html
{% extends "home/base.html" %}
{% load status %}

{% block title %}Send images{% endblock %}

{% block content %}
<h1>Send images on {{ issue.title }}</h1>
{% if user == issue.author %}
<ul class="nav nav-tabs">
  <li><a href="{% url 'issues:details' issue.id %}">Details</a></li>
  <li class="active"><a href="{% url 'issues:images' issue.id %}">Add images</a></li>
</ul>
{% endif %}
<form action="{% url 'issues:images' issue.id %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  
  {% for field in form %}
  <div class="form-group {% if field.errors %}has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    
    {{ field }}
    
    {% if field.errors %}
    <span class="help-block">{{ field.errors }}</span>
    {% endif %}
  </div>
  {% endfor %}
  
  <div class="form-group">
    <button type="submit" class="btn btn-primary">Upload image</button>
  </div>
</form>
{% endblock %}

angelhack/issues/templates/issues/index.html
{% load staticfiles %}
<!DOCTYPE html>

<html>
    <head>
        <title>Location API</title>
        <link rel="stylesheet" href="{% static 'issues/css/main.css' %}">
        <style>
            html, body {
              height: 100%;
              margin: 0;
              padding: 0;
            }
            #map {
              height: 100%;
            }
            .controls {
              margin-top: 10px;
              border: 1px solid transparent;
              border-radius: 2px 0 0 2px;
              box-sizing: border-box;
              -moz-box-sizing: border-box;
              height: 32px;
              outline: none;
              box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
            }

            #pac-input {
              background-color: #fff;
              font-family: Roboto;
              font-size: 15px;
              font-weight: 300;
              margin-left: 12px;
              padding: 0 11px 0 13px;
              text-overflow: ellipsis;
              width: 300px;
            }

            #pac-input:focus {
              border-color: #4d90fe;
            }

            .pac-container {
              font-family: Roboto;
            }

            #type-selector {
              color: #fff;
              background-color: #4d90fe;
              padding: 5px 11px 0px 11px;
            }

            #type-selector label {
              font-family: Roboto;
              font-size: 13px;
              font-weight: 300;
            }
            #target {
              width: 345px;
            }
        </style>
    </head>
    <body>
        <h1>Enter your location</h1>
        <form action="{% url 'issues:geolocation' %}" method="POST">
            {% csrf_token %}
            Latitude: <input type="text" name="lat" id="lat">
            Longitude: <input type="text" name="lng" id="lng">
            <input type="submit" value="Submit">
        </form>
        <input id="pac-input" class="controls" type="text" placeholder="Search Box">
        <div id="map"></div>
        <script src="https://code.jquery.com/jquery-2.2.3.min.js" integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=" crossorigin="anonymous"></script>
        <script src="https://maps.googleapis.com/maps/api/js?v=3&key=AIzaSyAqkdOCFGooUp--9EyjYr0DC-fiiBa3neg&callback=initMap"async defer></script>
        <script src="{% static 'issues/js/geolocation.js' %}"></script>
    <script>
      // This example adds a search box to a map, using the Google Place Autocomplete
      // feature. People can enter geographical searches. The search box will return a
      // pick list containing a mix of places and predicted search terms.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      function initAutocomplete() {
        // var map = new google.maps.Map(document.getElementById('map'), {
        //   center: {lat: -33.8688, lng: 151.2195},
        //   zoom: 13,
        //   mapTypeId: google.maps.MapTypeId.ROADMAP
        // });

        // Create the search box and link it to the UI element.
        var input = $('#pac-input')[0];
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        // Bias the SearchBox results towards current map's viewport.
        map.addListener('bounds_changed', function() {
          searchBox.setBounds(map.getBounds());
        });

        var markers = [];
        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();

          if (places.length == 0) {
            return;
          }

          // Clear out the old markers.
          markers.forEach(function(marker) {
            marker.setMap(null);
          });
          markers = [];

          // For each place, get the icon, name and location.
          var bounds = new google.maps.LatLngBounds();
          places.forEach(function(place) {
            var icon = {
              url: place.icon,
              size: new google.maps.Size(71, 71),
              origin: new google.maps.Point(0, 0),
              anchor: new google.maps.Point(17, 34),
              scaledSize: new google.maps.Size(25, 25)
            };

            // Create a marker for each place.
            markers.push(new google.maps.Marker({
              map: map,
              icon: icon,
              title: place.name,
              position: place.geometry.location
            }));

            if (place.geometry.viewport) {
              // Only geocodes have viewport.
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
          });
          map.fitBounds(bounds);
        });
      }

    </script>
    </body>
</html>

angelhack/issues/templates/issues/me.html
{% extends "home/base.html" %}
{% load status %}

{% block title %}My issues{% endblock %}

{% block content %}
<h1>My issues</h1>
{% if issues.count == 0 %}
<p>You didn't report any issues.</p>
{% else %}
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Tags</th>
      <th>Date submitted</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    {% for issue in issues %}
    <tr>
      <td><a href="{% url 'issues:details' issue.id %}">{{ issue.title }}</a></td>
      <td>{{ issue.category.title }}</td>
      <td>{{ issue.tags.all|join:", " }}</td>
      <td>{{ issue.date_created }}</td>
      <td>{{ issue.status|status_issue }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endif %}
{% endblock %}

angelhack/issues/templates/issues/submit.html
{% extends "home/base.html" %}
{% load staticfiles form_utils %}

{% block title %}Submit an issue{% endblock %}

{% block extracss %}
<link rel="stylesheet" href="{% static "home/css/select2.min.css" %}">
{% endblock %}

{% block content %}
<h1>Submit an issue</h1>
<form action="{% url 'issues:submit' %}" method="POST">
  {% csrf_token %}

  <div class="row">
    <div class="col-md-5">
      {% render_field form.title %}
    </div>
    <div class="col-md-7">
      {% render_field form.summary %}
      </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-8">
      {% render_field form.description %}
    </div>
    <div class="col-md-4">
      {% render_field form.category %}
      {% render_field form.tags %}
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-6">
      {% render_field form.latitude %}
    </div>
    <div class="col-md-6">
      {% render_field form.longitude %}
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div id="map"></div>
    </div>
  </div>
  <div class="row" style="margin-top:20px;">
    <div class="col-md-12">
      <div class="form-group">
	<button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</form>
{% endblock %}

{% block extrajs %}
<script src="{% static "home/js/select2.min.js" %}"></script>
<script>
  $(function(){
  $(".select2tags").select2({
  tags: true
  });
  $(".select2select").select2({});
  });
</script>
<script src="{% static 'issues/js/geolocation.js' %}"></script>
<style>
  #map {
  width: 100% !important;
  height: 300px !important;
  }
  .gm-style-iw + div {display: none;}
</style>
{% endblock %}