angelhack/angelhack/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^admin/', admin.site.urls),
    url(r'^issue/', include('issues.urls', namespace='issues')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

angelhack/home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sign-up$', views.signup, name='signup'),
    url(r'^sign-in$', views.signin, name='signin'),
    url(r'^sign-out$', views.signout, name='signout'),
    url(r'^daily-routine$', views.dailyroutine, name='routine'),
]

angelhack/home/models.py
from django.db import models

# Create your models here.

angelhack/home/forms.py
from django import forms
from django.contrib.auth.models import User

class UserSignUpForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def __init__(self, *args, **kwargs):
        super(UserSignUpForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})

class UserSignInForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def __init__(self, *args, **kwargs):
        super(UserSignInForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})

angelhack/home/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.core.urlresolvers import reverse
from .forms import *
import time
import datetime
from django.views.decorators.csrf import csrf_exempt
from issues.models import *
from django.template.loader import render_to_string
import requests

ua = 'Mozilla/5.0 (Linux; Android 6.0.1; MotoG3 Build/MPI24.107-55; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/49.0.2623.105 Mobile Safari/537.36'

def index(request):
    if request.user.is_authenticated():
        return redirect(reverse('issues:all'))
    return render(request, 'home/index.html')

def signup(request):
    if request.method == 'POST':
        form = UserSignUpForm(request.POST)
        if form.is_valid():
            if User.objects.filter(email=form.cleaned_data['email']).count() == 0:
                user = form.save()
                user.set_password(form.cleaned_data['password'])
                user.username = form.cleaned_data['first_name'] + form.cleaned_data['last_name'] + str(time.time()).split('.')[0]
                user.save()
                messages.success(request, "Your account has been created, you can now log in")
                return redirect(reverse('home:signin'))
            else:
                messages.error(request, "This email address is already taken")
        else:
            messages.warning(request, "Some data received are invalid")
    else:
        form = UserSignUpForm()
    return render(request, 'home/signup.html', {'form': form})

@csrf_exempt
def signin(request):
    # print(request.META.get("HTTP_USER_AGENT"))
    if request.method == 'POST':
        form = UserSignInForm(request.POST)
        if form.is_valid():
            try:
                username = User.objects.get(email=form.cleaned_data['email']).username
                user = auth.authenticate(username=username, password=form.cleaned_data['password'])
                if user is not None and user.is_active:
                    auth.login(request, user)
                    messages.success(request, "Your are now connected!")
                    return redirect(reverse('home:index'))
                else:
                    messages.warning(request, "No account found with these credentials")
            except (KeyError, User.DoesNotExist):
                    messages.warning(request, "No account found with these credentials")
        else:
            messages.warning(request, "Some data received are invalid")
    else:
        form = UserSignInForm()
    return render(request, 'home/signin.html', {'form': form})

def signout(request):
    auth.logout(request)
    messages.info(request, "You are now disconnected")
    return redirect(reverse('home:signin'))

def send_mail(to, subject, content):
    requests.post(
        'https://api.mailgun.net/v3/sandboxaa42a819db5c4a8f8ab17535ceffe0ab.mailgun.org/messages',
        auth=("api", 'key-942d65f04a3923ebbd2f27573e797485'),
        data={"from": 'Team Find Figam' + " <report@findfigam.com>",
              "to": to,
              "subject": subject,
              "html": content
          })

def dailyroutine(request):
    categories = Category.objects.all()
    for category in categories:
        yesterday = datetime.date.today() - datetime.timedelta(days=1)
        issues = Issue.objects.filter(date_created__gt=yesterday, category=category)
        tpl = render_to_string('home/dailyroutine.html', {'issues':issues, 'category': category, 'date_today': datetime.date.today()})
        send_mail([category.respected.email], "Report of the day", tpl)
    return HttpResponse("done")

angelhack/home/templates/home/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "home/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "home/css/font-awesome.min.css" %}">
    <title>{% block title %}{% endblock title %} - Find Figam</title>
    {% block extracss %}{% endblock extracss %}
  </head>
  <body>
    
    
    
    <!-- start -->
    
    <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
	  <span class="icon-bar"></span>
	  <span class="icon-bar"></span>
	  <span class="icon-bar"></span>
	</button>
	<a class="navbar-brand" href="/">Find Figam</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse" style="height: 1px;">
	{% if user.is_authenticated %}
	<ul class="nav navbar-nav">
	  <li><a href="/issue/submit"><span class="fa fa-plus"></span> Submit an issue</a></li>
	  <li><a href="/issue/me"><span class="fa fa-star"></span> My issues</a></li>
	  <li><a href="/issue/all"><span class="fa fa-list"></span> All issues</a></li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
	  <li><a href="/sign-out"><span class="fa fa-sign-out"></span> Sign out</a></li>
	</ul>
	<p class="hidden-xs navbar-text navbar-right">Hello <b>{{ user.first_name }}</b>!</p>
	{% else %}
	<ul class="nav navbar-nav">
	  <li><a href="/issue/submit"><span class="fa fa-plus"></span> Submit an issue</a></li>
	  <li><a href="/issue/me"><span class="fa fa-star"></span> My issues</a></li>
	  <li><a href="/issue/all"><span class="fa fa-list"></span> All issues</a></li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
	  <li><a href="/sign-in"><span class="fa fa-user"></span> Sign in</a></li>
	  <li><a href="/sign-up"><span class="fa fa-user-plus"></span> Sign up</a></li>
	</ul>
	{% endif %}
      </div>
    </div>
    </nav>
  
    <!-- end -->
    <section id="pageContent" style="padding-top:40px;" class="container">
      {% if messages %}
      <div style="margin-top:20px;">
	{% for message in messages %}
	<div {% if message.tags %}class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
	{% endfor %}
      </div>
      {% endif %}
      {% block content %}{% endblock content %}
    </section>
    <script src="{% static "home/js/jquery.min.js" %}"></script>
  <script src="{% static "home/js/bootstrap.min.js" %}"></script>
  {% block extrajs %}{% endblock extrajs %}
  </body>
</html>

angelhack/home/templates/home/dailyroutine.html
{% load status %}

<h1>Report of the day {{ date_today }}</h1>
<h2>Category {{ category.title }}</h2>
{% if issues.count == 0 %}
<p>There was no issues reported today.</p>
{% else %}
<table>
    <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Tags</th>
      <th>Date submitted</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    {% for issue in issues %}
    <tr>
      <td>{{ issue.title }}</td>
      <td>{{ issue.author.email }}</td>
      <td>{{ issue.tags.all|join:", " }}</td>
      <td>{{ issue.date_created }}</td>
      <td>{{ issue.status|status_issue }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endif %}

angelhack/home/templates/home/index.html
{% extends "home/base.html" %}
{% load staticfiles %}

{% block title %}Home{% endblock %}


{% block content %}
<div class="jumbotron text-center">
  <h1>Report It. They Fix It.</h1>
  <p class="lead">This App provides the citizens with the flexibility to lodge their complaints anywhere and anytime.</p>
  <p><a class="btn btn-lg btn-success" href="{% url 'home:signup' %}">Sign up</a></p>
</div>
{% endblock %}

angelhack/home/templates/home/signin.html
{% extends "home/base.html" %}
{% load staticfiles %}

{% block title %}Sign in{% endblock %}


{% block content %}
    <h1>Sign in</h1>
    <form action="{% url 'home:signin' %}" method="POST">
        {% csrf_token %}

        {% for field in form %}
        <div class="form-group {% if field.errors %}has-error{% endif %}">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>

            {{ field }}

            {% if field.errors %}
                <span class="help-block">{{ field.errors }}</span>
            {% endif %}
        </div>
        {% endfor %}

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Sign in</button>
        </div>
    </form>
{% endblock %}

angelhack/home/templates/home/signup.html
{% extends "home/base.html" %}
{% load staticfiles %}

{% block title %}Sign up{% endblock %}


{% block content %}
    <h1>Sign up</h1>
    <form action="{% url 'home:signup' %}" method="POST">
        {% csrf_token %}

        {% for field in form %}
        <div class="form-group {% if field.errors %}has-error{% endif %}">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>

            {{ field }}

            {% if field.errors %}
                <span class="help-block">{{ field.errors }}</span>
            {% endif %}
        </div>
        {% endfor %}

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Sign up</button>
        </div>
    </form>
{% endblock %}